services:
  productdb:
    image: mongo

  shoppingCartdb:
    image: postgres
 
  distributedShoppingCartcache:
    image: redis

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services/Product/Product.API/Dockerfile

  shoppingcart.api:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: Services/ShoppingCart/ShoppingCart.API/Dockerfile

volumes:
      mongo_productdb:
      postgres_shoppingCartdb:

